@startuml

participant "Node" as N
participant "Multiplex Transport" as MT

box "Switch"
participant "acceptRoutine" as AR
participant "DialPeerWithAddress" as DPWA
participant "addPeer" as AP
participant "dialPeersAsync" as DPA
participant "reconnectToPeer" as RTP
participant "StopPeerForError" as SPFE
end box

box "P2P.Peer"
participant "Peer" as PR
end box

participant "Reactor" as RC

N -> MT: Listen (node/node.go#L550)
N -> AR: Start (node/node.go#L557)
AR -> RC : Start (p2p/switch.go#L237)
AR -> MT: Accept (p2p/switch.go#L635)
MT -> PR: newPeer (p2p/transport.go#L526)
PR -> MT: new Peer with connection (p2p/peer.go#L169)
MT -> AR: Peer With Connection (p2p/switch.go#L635)
AR -> AP: Peer With Connection (p2p/switch.go#L709)

N -> DPA: Dial and Update Address book (node/node.go#L563)

DPA ->> DPWA: address (p2p/switch.go#L534)

DPWA -> MT : Dial (p2p/switch.go#L740)
MT -> MT : Upgrade Connection with\nAuthenticated Encryption Handshake (p2p/transport.go#L231)
MT -> DPWA: Dial Success (p2p/switch.go#L740)
DPWA -> AP: Add Active Peer (p2p/switch.go#L770)

AP -> PR: Start (p2p/switch.go#L834)
AP -> AP: Add to peer set (p2p/switch.go#L844)
AP -> RC: Add Peer (p2p/switch.go#L857)

PR ->> RC: Receive - onreceive callback (p2p/peer.go#425)
RC ->> PR: Send (p2p/pex/pex_ractor.go#L343)

RC ->> SPFE: onPeerError (p2p/peer.go#L271#L282)

RC -> SPFE  : Pax address or request error (p2p/pex/pex_ractor.go#L271#L282#L288)
SPFE ->> RTP  : addr to reconnect (p2p/switch.go#L356)
RTP ->> DPWA : addr to reconnect (p2p/switch.go#436#412)

DPWA -> MT: Dial (p2p/switch.go#L740)
MT -> DPWA: Dial Success (p2p/transport.go#240)
DPWA -> AP: Add Active Peer (p2p/switch.go#L844)

AP -> RC: Add Peer (p2p/switch.go#L857)

SPFE ->> RTP: Retry connection (p2p/switch.go#356)
SPFE -> RC: stopAndRemovePeer (p2p/switch.go#L374)
SPFE -> PR: Stop (p2p/switch.go#369)



@endtuml