@startuml

participant "Node" as N
participant "Multiplex Transport" as MT

box "Switch"
participant "acceptRoutine" as AR
participant "DialPeerWithAddress" as DPWA
participant "addPeer" as AP
participant "dialPeersAsync" as DPA
participant "reconnectToPeer" as RTP
participant "StopPeerForError" as SPFE
end box

box "P2P.Peer"
participant "Peer" as PR
end box

participant "Reactor" as RC

N -> MT: Listen (node/node.go)
N -> AR: Start (node/node.go)
AR -> RC : Start (p2p/switch.go)
AR -> MT: Accept (p2p/switch.go)
MT -> PR: newPeer (p2p/transport.go)
PR -> MT: new Peer with connection (p2p/peer.go)
MT -> AR: Peer With Connection (p2p/switch.go)
AR -> AP: Peer With Connection (p2p/switch.go)

N -> DPA: Update Address book and Dial (p2p/transport.go)

DPA ->> DPWA: address (p2p/switch.go)

RC ->> SPFE: onPeerError (p2p/peer.go)

DPWA -> MT : Dial (p2p/pex/pex_reactor.go)
MT -> MT : Upgrade Connection with\nAuthenticated Encryption Handshake (p2p/transport.go)
MT -> DPWA: Dial Success (p2p/switch.go)
DPWA -> AP: Add Active Peer (p2p/switch.go)


AP -> AP: Add to peer set (p2p/switch.go)
AP -> PR: Start (p2p/switch.go)
AP -> RC: Add Peer (p2p/switch.go)

PR ->> RC: Receive (p2p/peer.go)
RC ->> PR: Send (p2p/peer.go)


RC -> SPFE  : RemovePeer (p2p/pex/pex_reactor.go)
SPFE -> RTP  : addr to reconnect (p2p/switch.go)
RTP -> DPWA : addr to reconnect (p2p/switch.go)

DPWA -> MT: Dial (p2p/switch.go)
MT -> DPWA: Dial Success (p2p/transport.go)
DPWA -> AP: Add Active Peer (p2p/switch.go)

AP -> RC: Add Peer (p2p/switch.go)

MT -> MT: Retry connection (p2p/transport.go)


MT -> DPWA: ErrorPersists (p2p/transport.go)
DPWA -> SPFE: onError (p2p/switch.go)

SPFE -> PR: Stop (p2p/switch.go)



@endtuml